filter:
    excluded_paths:
        - "bin/"
        - "config/"
        - "node_modules/"
        - "public/"
        - "templates/"
        - "tests/"
        - "translations/"
        - "var/"
        - "vendor/"
build:
    environment:
        php:
            version: 7.1.12

checks:
    php:
        code_rating: true
        duplication: true

